### ISSUE TITLE
Web Chat option for Jabber, Integrate with Core services

### ISSUE THREAD

**Issue by squadbroken** [bravecollective/IT-Projects#15]
Setting up Jabber is significant effort for casual/less technical users, even with the guide and screenshot.

A Webchat alternative, integrated with CORE, would allow them to get online easily and has a very low barrier to entry.

https://conversejs.org is highly recommended

https://conversejs.org/docs/html/setup.html#session-support for details on integration with existing services

**Comment by tkhamez** [comment]
We don't use Jabber anymore.
