### ISSUE TITLE
New BLT web app

### ISSUE THREAD

**Issue by Okko-Tolea** [bravecollective/IT-Projects#18]
Features needed : 
- welcome page or area with intro text
- select origin point and destination from pick lists
- Input of collateral and volume
- Calculation of reward based on distance covered and number of jumps to be made
- Sso login with neucore
- Basic stats page for any brave member (number of contracts outstanding, in progress, completed last 3 days)
- outstanding contracts page accessible only to character in BLT corporation (list of contracts available with key info including color coding or other verification system on contract correct rewards / systems used)
- admin panel only for BLT directors : add/remove destinations, edit reward calculation formula, advanced stats as above but including a view by hauler

**Comment by tkhamez** [comment]
It would be good if systems could be excluded when calculating the route used to calculate the reward, e.g. systems without blue structures. Or maybe the other way around: only use systems that are predefined?

**Comment by Okko-Tolea** [comment]
I think we only use set systems (as it used to be).
Hence my request to have an admin page where we can add/remove available destinations / origins.

**Comment by tkhamez** [comment]
Sure, but the route may need mids, you want to be able to restrict those too, because the reward is based on the length of the route.

**Comment by Okko-Tolea** [comment]
Yeah that makes sense. 

Additional feature (probably for a V2) : allow anyone who logs in to see their open contracts (check that is is made correctly, how many in progress, how many outsanding). Similar to the view reserved for BLT members but only for one's personal contracts.

**Comment by tkhamez** [comment]
Pip Kouvo

**Comment by tkhamez** [comment]
Izakbar

**Comment by chrishenschel** [comment]
I would add a direct connection to the appraisal tool. Just copy and paste your stuff, let the tool do the math (volume, collateral) and then just tell it which route and done. Manually calculating those values feels horrible :/

**Comment by tkhamez** [comment]
https://github.com/bravecollective/project-freight-train
