### ISSUE TITLE
Doctrineships - enhance admin functionality

### ISSUE THREAD

**Issue by kiu** [bravecollective/IT-Projects#5]
a. Allow in-browser editing of ship fits, especially for those fits with 0 contracts
  I. Allow EFT format as well as XML
  II. Some kind of "phase out" feature could be suggested for editing ships with existing contracts.  The old fit would be set to expire in a week or two, and the new fit would be added to all the same doctrines as the old with an effective date.
b. Allow adding 1 ship to several doctrines at once.
c. Display the doctrines a shipfit belongs to on the shipfit page.
d. Allow a way to clear the cache, allowing the user to see the immediate results of their work

Customer: Serinus Gareth
Source: https://github.com/Serinus1/doctrineships

**Comment by tkhamez** [comment]
We don't use this app anymore, doctrine fits are on the Wiki now.
