### ISSUE TITLE
CORE - Tell Internet Explorer users to go away

### ISSUE THREAD

**Issue by kiu** [bravecollective/IT-Projects#7]
The support team receives quite some tickets where people fail to login/reset their core account due to the fact that they use Internet Explorer.

Inform visitors using Internet Explorer that they are bad and should feel bad.

Example: http://eve.501gu.de/ie-kitten/
Customer: Acid Katelo
Source: https://github.com/bravecollective/core/

**Comment by tkhamez** [comment]
In the meantime CCP told CORE to go away :) - XML API has been replaced by ESI.
RIP core, neucore support IE11.
