### ISSUE TITLE
Doctrineships - Authenticate through CORE

### ISSUE THREAD

**Issue by kiu** [bravecollective/IT-Projects#8]
The current method of authentication through links is wildly unpopular, and core integration is desirable anyway. We should maintain a method of using the site's in-game tools.

If [Core in IGB](https://github.com/bravecollective/IT-Projects/issues/6) is resolved, CORE could be directly incorporated into DS.

Otherwise a mechanism providing a unique authentication link for DS could be generated on a CORE enabled site for OGB usage. Users could then use this link for DS to authenticate while using IGB.

Customer: Serinus Gareth
Source: https://github.com/Serinus1/doctrineships

**Comment by tkhamez** [comment]
We no longer use either program.
