### ISSUE TITLE
Military - Offer our userbase a skillchecker

### ISSUE THREAD

**Issue by kiu** [bravecollective/IT-Projects#9]
Similar to: http://skills.pleaseignore.com/
- Show users BRAVE doctrine ships and indicate if they fulfill minimal/optiomal skill requirements as determined by the FC team.
- Let users export skill requirements in evemon format
- Generate statistics for our military department (how many can fly what, what skill level do people have to match new doctrines, etc)

This could be integrated into doctrineships.com.

Customer: FC Team

**Comment by beatbandolier** [comment]
Finally got started this week.  RL has been a bear (baer?) since Christmas.
